Traceback (most recent call last):
  File "/Users/eddifying/micromamba/envs/seaocn_env/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/eddifying/micromamba/envs/seaocn_env/lib/python3.8/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/eddifying/micromamba/envs/seaocn_env/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/eddifying/micromamba/envs/seaocn_env/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/eddifying/micromamba/envs/seaocn_env/lib/python3.8/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/eddifying/micromamba/envs/seaocn_env/lib/python3.8/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/eddifying/micromamba/envs/seaocn_env/lib/python3.8/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
print('Velocity magnitude vector is '+str(ds.magnitude.shape))
print('Time vector is '+str(ds.time.shape))
print('Depth vector is '+str(ds.depth.shape))

interval_secs = np.diff(ds.time).mean()/ np.timedelta64(1, 's')
print('Time interval in seconds is '+str(interval_secs))
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[8], line 1[0m
[0;32m----> 1[0m [38;5;28mprint[39m([38;5;124m'[39m[38;5;124mVelocity magnitude vector is [39m[38;5;124m'[39m[38;5;241m+[39m[38;5;28mstr[39m([43mds[49m[38;5;241m.[39mmagnitude[38;5;241m.[39mshape))
[1;32m      2[0m [38;5;28mprint[39m([38;5;124m'[39m[38;5;124mTime vector is [39m[38;5;124m'[39m[38;5;241m+[39m[38;5;28mstr[39m(ds[38;5;241m.[39mtime[38;5;241m.[39mshape))
[1;32m      3[0m [38;5;28mprint[39m([38;5;124m'[39m[38;5;124mDepth vector is [39m[38;5;124m'[39m[38;5;241m+[39m[38;5;28mstr[39m(ds[38;5;241m.[39mdepth[38;5;241m.[39mshape))

[0;31mNameError[0m: name 'ds' is not defined

